//-----------------------------------------------------------------------------
// sweep_ctrl.sv  (INSTRUCTOR-PROVIDED, STUDENTS DO NOT MODIFY)
//-----------------------------------------------------------------------------
// Window sweep controller for the claw game.
// Drives an N_LEDS-bit "window" that moves left <-> right across the LED row.
//
// This module is clocked by a SLOW CLOCK generated by clkdivN.
// Top-level is responsible for:
//   - instantiating clkdivN
//   - connecting its slow output to sweep_clk
//
// Interface:
//   - rst_n      : asynchronous active-low reset
//   - sweep_clk  : slow clock (e.g., from clkdivN)
//   - sweep_en   : when 1, the window moves on each sweep_clk edge
//   - led_window : current window mask to drive LEDR[17:0]
//
// Behavior:
//   - Window is a small group of adjacent 1 bits (WIN_WIDTH-wide) that bounces
//     between the left and right ends of the LED row.
//   - When sweep_en = 0, the window holds its current position and direction.
//-----------------------------------------------------------------------------

module sweep_ctrl #(
    parameter int N_LEDS    = 18,
    parameter int WIN_WIDTH = 3    // number of consecutive LEDs in the window
) (
    input  logic              rst_n,       // async active-low reset
    input  logic              sweep_clk,   // slow clock from clkdivN
    input  logic              sweep_en,    // enable sweeping
    output logic [N_LEDS-1:0] led_window   // window LED mask (to LEDR[17:0])
);

    // Current window position/mask
    logic [N_LEDS-1:0] window_reg;

    // Direction: 1 = moving toward higher index (to the right),
    //            0 = moving toward lower index (to the left)
    logic dir;

    //--------------------------------------------------------------------------
    // Sweep logic: update window on each rising edge of the slow clock
    // with asynchronous reset
    //--------------------------------------------------------------------------
    always_ff @(posedge sweep_clk, negedge rst_n) begin
        if (!rst_n) begin
            // Reset: start with the window at the left side:
            // bits [WIN_WIDTH-1:0] = 1, everything else 0
            window_reg                  <= '0;
            window_reg[WIN_WIDTH-1:0]   <= {WIN_WIDTH{1'b1}};
            dir                         <= 1'b1; // start moving "right"
        end
        else if (!sweep_en) begin
            // Hold position and direction when disabled
            window_reg <= window_reg;
            dir        <= dir;
        end
        else begin
            // Check if window is at the left or right edge
            logic at_left_edge;
            logic at_right_edge;

            at_left_edge  = (window_reg[WIN_WIDTH-1:0] == {WIN_WIDTH{1'b1}})
                            && (window_reg[N_LEDS-1:WIN_WIDTH] == '0);

            at_right_edge = (window_reg[N_LEDS-1 -: WIN_WIDTH] == {WIN_WIDTH{1'b1}})
                            && (window_reg[N_LEDS-WIN_WIDTH-1:0] == '0);

            if (dir) begin
                // Moving right (toward higher indices)
                if (at_right_edge) begin
                    // Bounce: reverse direction and move one step left
                    dir        <= 1'b0;
                    window_reg <= window_reg >> 1;
                end else begin
                    // Normal move to the right
                    window_reg <= window_reg << 1;
                end
            end else begin
                // Moving left (toward lower indices)
                if (at_left_edge) begin
                    // Bounce: reverse direction and move one step right
                    dir        <= 1'b1;
                    window_reg <= window_reg << 1;
                end else begin
                    // Normal move to the left
                    window_reg <= window_reg >> 1;
                end
            end
        end
    end

    // Drive output
    assign led_window = window_reg;

endmodule
